### ISSUE TITLE
Cover possible problem with NamedDomainObjectContainer

### ISSUE THREAD

**Issue by gildor** [gradle-guides/migrating-build-logic-from-groovy-to-kotlin#13]
Currently, one of the biggest confusions, when you migrate from Groovy to Kotlin, is aproblem with converting from `NamedDomainObjectContainer` to `NamedDomainObjectContainerScope` in some plugins.
Given:
To have nice invoke syntax for NamedDomainObjectContainer like:
```
someContainer {
  "someItem" { /*type safe config*/ }
}
```
Kotlin DSL uses invoke operator overloading for NamedDomainObjectContainer, that converts it to NamedDomainObjectContainerScope which provides `String.invoke()` operator.
This syntax may look strange, but very close too groovy and very concise and still type safe.

Problem:
But some plugins also provide not only `getSomeContainer(): NamedDomainObjectContainer<T>` property but configuration block with type something like:
```
void someContainer(Action<? super NamedDomainObjectContainer<T>> action)
```
So, provide native support for configuration of NamedDomainObjectContainer,
but this doesn't allow to use invoke operator, as result you cannot use invoke syntax and don't have access to String.invoke operator and you should use explicit `maybeCreate()` or `getByName()`, but those methods don't provide lambda with Action to configure them, so you can use Kotlin `apply` extension.
So final workaround looks something like:
```
someContainer {
  maybeCreate("someItem").apply { /*type safe config*/ }
}
```

Not so bad, but still noisy.

And one big example of such problem is the Android Gradle plugin, where we have `android.buildTypes` and `android.signingConfigs` DSL. Both of those DSL available as methods with `Action<NamedDomainObjectContainer<T>>`, so by default no access to String.invoke syntax

Fortunately, Android Gradle Plugin also provide public getter `getSigningConfigs()`, so we can use another workaround: use `invoke` extension explicitly or parenthesizes:
```
android {
  (buildTypes) { // this: NamedDomainObjectContainerScope ->
       "debug" {} 
   }
   //or
   signingConfigs.invoke { // this: NamedDomainObjectContainerScope ->
      "release" {}
   }
}

```

But it's not always the case for other plugins some of them doesn't provide a method with `Action<NamedDomainObjectContainer<T>>` and the only way is to use workarounds with explicit invoke or parenthesizes.

But what is really bad is that if the method is not available and when nested ObjectContainer name clashes with some top-level property, really bad example of this can be found in official gradle [publish-plugin](https://plugins.gradle.org/docs/publish-plugin). So if you just use `plugin` container in publish-plugin dsl will be resolved top level `plugins` block and of course, you cannot define plugin
Fortunately, official documentation now has Kotlin-DSL snippet and uses a workaround with parenthesizes, but It still not so obvious.

Proposal:
I think the official migration guide should cover this problem and suggest solutions as for end users of official and third-party plugins as well as a guide for plugins authors how to avoid this problem.
Maybe make sense to solve this somehow at least for official Gradle plugins and for very popular Android Plugin.
For now would be also good to add links to the corresponding issue of plugins and probably to some discussion where we can discuss how to solve this problem completely.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #279](https://github.com/gradle/guides/issues/279) via [**ZenHub**](https://www.zenhub.com/)
