### ISSUE TITLE
Some findings about the guide while reading 

### ISSUE THREAD

**Issue by StefMa** [gradle-guides/migrating-build-logic-from-groovy-to-kotlin#14]
I just wanted to report some "findings" which I think should be changed/is misleading or something similar.

1. No one needs that Tip. It is clear that the user can do this. 
![bildschirmfoto 2018-07-12 um 07 42 59](https://user-images.githubusercontent.com/10229883/42614683-3975024c-85a7-11e8-81d0-67eca041dcef.png)
**Solution**: Remote it

2. Should be the `apply()` a `apply<Plugin>()` here?
![bildschirmfoto 2018-07-12 um 07 43 54](https://user-images.githubusercontent.com/10229883/42614737-6abac698-85a7-11e8-9389-cf9ecfa478c8.png)
Even if its not recommended to use the `apply` function. When should I use `apply(name)` and when `apply<Plugin>()`?
**Solution:** Either change it or document when to use what

3. In the "configuration plugin" section this is the build script:
![bildschirmfoto 2018-07-12 um 07 45 32](https://user-images.githubusercontent.com/10229883/42614773-99afc3ae-85a7-11e8-8de7-638a9dc62f90.png)
This is wrong, right? "just writing jacoco" isn't possible, right? Should be either `jacoco` (with the tick (\`) but I can't write in code at github 😁) or `id("jacoco")`. 
**Solution**: Use `id("jacoco")` here because in a section above you say that that is the way to go. Using now just `jacoco` (with tick(\`)) is just confusing.
## Update to 3:
The groovy & kotlin style is mixed 🙃 Should be changed:
![geist_1531374646565](https://user-images.githubusercontent.com/10229883/42614943-56e878b2-85a8-11e8-9309-a1058da01a46.gif)

4. I guess the Android Plugin have some dependencies which are in jcenter. I think we have to add this here too. Or does the `gradlePluginPortal` redirect to jcenter correctly here?
![bildschirmfoto 2018-07-12 um 07 52 50](https://user-images.githubusercontent.com/10229883/42615045-b8364a68-85a8-11e8-937a-0382099c8af5.png)

5. I still don't get the benefit of the Kotlin delegation  for tasks.
`tasks.create()` returns a task either. Why do you prefer `by tasks.creating`? 
```
val awesomeTask = tasks.create("awesomeTask")
```
Is the same, right?
![bildschirmfoto 2018-07-12 um 07 58 36](https://user-images.githubusercontent.com/10229883/42615212-677e0dee-85a9-11e8-9e2f-0795eee2697e.png)

6. The `java` applying is wrong. Similar issue like 3 without an update 🙃 
![bildschirmfoto 2018-07-12 um 07 59 14](https://user-images.githubusercontent.com/10229883/42615227-805ba812-85a9-11e8-96dd-37dcf7537ad7.png)

7. In the configuration section. Why not using `configuration.create()`?
![bildschirmfoto 2018-07-12 um 08 01 10](https://user-images.githubusercontent.com/10229883/42615286-cc42ebb4-85a9-11e8-86a3-f5c836718749.png)

That is all for now 😇

**Comment by gildor** [comment]
> just writing jacoco" isn't possible, right
No, it's completely valid and better way to apply core plugins (type-safe and with autocomplete). You can use statically-typed accessors for all core plugins

**Comment by eskatos** [comment]
About `#5` and `#7`, using delegated properties allow you to DRY, not to repeat the task name. It also means that you can use your IDE to eventually refactor/rename the task directly.

**Comment by StefMa** [comment]
Closed - everything is fixed/clarified/explained
