### ISSUE TITLE
Switching between Groovy and Kotlin causes content to jump drastically.

### ISSUE THREAD

**Issue by philburtenshaw** [gradle-guides/migrating-build-logic-from-groovy-to-kotlin#16]
At the begging of the guide, the code samples line up exactly, and when switching between gradle and kotlin, are very easy to read and to observe differences between them.

However, after the section labelled [Creating Tasks](https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/?_ga=2.258929869.631885918.1531898677-1253513468.1526886005#creating_tasks), the content is offset vertically, and switching between the two languages becomes extremely difficult to follow.

This became very distracting from the content.

**Comment by eriwen** [comment]
Issue moved to [gradle-guides/gradle-guides-plugin #28](https://github.com/gradle-guides/gradle-guides-plugin/issues/28) via [**ZenHub**](https://www.zenhub.com/)

**Comment by eriwen** [comment]
Thanks for this issue @philburtenshaw. I'll fix for all guides in the gradle guides plugin.
