### ISSUE TITLE
Explain how to mix Groovy/Kotlin project scripts when not using the default script names

### ISSUE THREAD

**Issue by eskatos** [gradle-guides/migrating-build-logic-from-groovy-to-kotlin#19]
without hitting the disk in the settings file.

Good
https://github.com/gradle/gradle/blob/dd3e28584484fe44ca19f9d25b794d464aef800c/settings.gradle.kts#L110-L184

Bad
https://github.com/gradle/dotcom/blob/5aa75173ff84d13d597761c64ce1de87b296e0a8/settings.gradle.kts#L87

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #280](https://github.com/gradle/guides/issues/280) via [**ZenHub**](https://www.zenhub.com/)
