### ISSUE TITLE
Feedback on the first version

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/migrating-build-logic-from-groovy-to-kotlin#2]
@eskatos Good work on the guide!

Here's some feedback on what I currently see in https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/.

- Let's not number headings. We don't do this in the other guides. 
- Use full proper when referring to IntelliJ IDEA rather than IntelliJ which is the former name of the company behind it.
- It would be great to include a short screencast demonstrating the IDE support. WDYT, @eriwen?
- Shouldn't we recommend Eclipse and NetBeans users not to migrate at this time? Currently, we say that you can do that but you don't get code completion etc. What's the point then?
- I'd considering saying something like applying plugins with `plugins` block is strongly recommended when using the Kotlin DSL.
- It was mentioned before in other discussions but we need to decide what are recommened ways to create and configure tasks.

**Comment by eskatos** [comment]
> It would be great to include a short screencast demonstrating the IDE support. WDYT, @eriwen?

I'm not sure this guide is the right place for this. I'll let @eriwen weight in.

> Shouldn't we recommend Eclipse and NetBeans users not to migrate at this time? Currently, we say that you can do that but you don't get code completion etc. What's the point then?

What we say is basically that using the Kotlin DSL won't break Gradle integrations but that you won't get the IDE goodness. I'm in favor of keeping it that way but no strong opinion. Please suggest rephrased content if you feel strongly about it.

> It was mentioned before in other discussions but we need to decide what are recommened ways to create and configure tasks.

The guide currently demonstrates both the Gradle API usage and the Kotlin DSL delegated properties sugar. The sugar helps with not repeating task names, which is great and more solid when it comes to refactoring. I strongly think we should not underestimate the audience and that we should keep the sugar documentation.

Other points addressed in #4

**Comment by eriwen** [comment]
I think we should have a screencast showing how awesome the Kotlin DSL is, but the migration guide is probably not the right place for it. 

So I tried out a Kotlin DSL file using the very latest Gradle and Eclipse (Oxygen 3a) with the [kotlin-eclipse plugin](https://github.com/JetBrains/kotlin-eclipse). I basically get no IDE support.

![screenshot 2018-06-21 15 42 15](https://user-images.githubusercontent.com/51534/41749176-ea37fe7a-7569-11e8-82ec-abdc3536fe9c.png)

We _must_ discourage users from adopting something that is going to make UX worse. We can change the text when the situation improves. The degradation is bad enough that I think we're going to need a disclaimer in more than just this guide, I think.

**Comment by eskatos** [comment]
@eriwen done in https://github.com/gradle-guides/migrating-build-logic-from-groovy-to-kotlin/commit/9746d8edd20775d8b6e203f458b99fdf1791af47#diff-26e5159b22409dca66bbd718ccd8cc72R139

Closing this issue as addressed
