### ISSUE TITLE
The "kotlin-dsl samples" link under next steps is broken

### ISSUE THREAD

**Issue by ianbrandt** [gradle-guides/migrating-build-logic-from-groovy-to-kotlin#22]
https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/#next_steps

**Comment by eskatos** [comment]
Thank you for the report @ianbrandt, fixed in https://github.com/gradle-guides/migrating-build-logic-from-groovy-to-kotlin/commit/6f5588c460173dae31e1b19eb3d4acbbdc259ffc
