### ISSUE TITLE
mention how to install kotlin-gradle-plugin in plugins block

### ISSUE THREAD

**Issue by keturn** [gradle-guides/migrating-build-logic-from-groovy-to-kotlin#26]
The guide says

> Use of the `plugins {}` block to declare Gradle plugins significantly improves the editing experience, and is highly recommended. Consider adopting it in your Groovy build scripts before converting them to Kotlin.

so I tried doing that first. Since my project is a Kotlin project, one of the plug-ins I had to use in the `plugins` block is the Kotlin one.

It's not a core plugin in, and though it was `kotlin-gradle-plugin` when I was adding it to my classpath in the buildscript block, that's not the name it goes by in the Gradle plug-ins repo, so I stumbled over that for a while.

It also wasn't clear to me whether, in my multi-project build, that I still needed to `apply` the plugin in my projects (since the `plugins` block is documented as auto-applying them by default), and if so, which name I use there. (is it still `"kotlin"` or is it the longer ID that is used in the plugins block?)

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #281](https://github.com/gradle/guides/issues/281) via [**ZenHub**](https://www.zenhub.com/)
