### ISSUE TITLE
Expand and clarify information on configuring plugins 

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/migrating-build-logic-from-groovy-to-kotlin#3]
Following up on https://github.com/gradle-guides/migrating-build-logic-from-groovy-to-kotlin/issues/2, here's a couple of more points regarding the https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/#configuring_plugins section.

I miss a mention of configuring plugins through task configuration. This is a pretty common pattern and I found it to be a gotcha when converting from Groovy to Kotlin DSL because it's done differently and it's not obvious which way you should configure the plugin without looking into its source code. 

Secondly, I think combining two ways of applying and configuring a plugin in a single code sample doesn't help with the clarity. I'd split it into two paragraphs, preferably with a single plugin and equalivent configuration used as an example: 
1) `plugins` block with extension functions 
2) `apply` and `configure<T> {}`

I'd also make it it clear that the first is the preferred way.

**Comment by eskatos** [comment]
Thanks for the feedback @pioterj.
Addressed in #4.

**Comment by eskatos** [comment]
#4 merged, closing
