### ISSUE TITLE
Consider adding a prominent, initial, “why” section 

### ISSUE THREAD

**Issue by ldaley** [gradle-guides/migrating-build-logic-from-groovy-to-kotlin#7]
I think it would be worth succinctly communicating to users in this document why they might want to migrate. I think this should be in addition to the existing content.

I don't think we should assume that everyone is with us on this journey. We need to help people understand why they should care, and make that easy for them.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #277](https://github.com/gradle/guides/issues/277) via [**ZenHub**](https://www.zenhub.com/)
