### ISSUE TITLE
Code samples should show kotlin version as default

### ISSUE THREAD

**Issue by breskeby** [gradle-guides/migrating-build-logic-from-groovy-to-kotlin#9]
It would be better to show the kotlin version of code samples by default than the groovy version. By default currently all build script samples show the groovy version. this is misleading. Especially when you don't read the full guide but are just looking for sample snippets (which users do).

**Comment by eskatos** [comment]
The switch is global to all our documentation properties, not local to this guide.

@eriwen any idea if we could make this guide force-switch to Kotlin DSL samples on load and if it sounds like a valid approach?

**Comment by eriwen** [comment]
The machinery remembers one's selections. I think it's pretty clear that there are tabs that say "groovy" and "kotlin" for a reason. I think this might be a bit too speculative at this point to take action on. 

I can achieve this @eskatos but it requires at least a few hours of initial investment and then continued maintenance forever. If one were especially passionate, a pull request to update the JavaScript in gradle/guides would be place to start. I would recommend using some kind of asciidoctor attribute to control the behavior per-guide.

**Comment by eskatos** [comment]
Thanks @eriwen, makes sense.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #278](https://github.com/gradle/guides/issues/278) via [**ZenHub**](https://www.zenhub.com/)
